// Contornos novos do auditor_b1_d1_8 contra os analisadores atuais (K3/K4), em pasta temporária.
import { analisarSeguranca } from '../../../base/verificacao/seguranca-estatica.mjs'
import { analisar as rede } from '../../../base/verificacao/saida-de-rede.mjs'
const nc = (f) => analisarSeguranca(f, 'next.config.ts')
const c = (id, desc, a) => console.log(`${id} | ${desc} | ${a.length ? 'CAUGHT | ' + a[0].motivo : 'SURVIVED'}`)
c('XN09a', 'assetPrefix por shorthand de const lida do ambiente', nc("const assetPrefix = process.env.DOMINIO_A_URL\nexport default { assetPrefix }"))
c('XN09b', 'config.assetPrefix = process.env.X (atribuicao)', nc("const config = {}\nconfig.assetPrefix = process.env.DOMINIO_A_URL\nexport default config"))
c('XN09d', "chave calculada ['assetPrefix']", nc("export default { ['assetPrefix']: process.env.DOMINIO_A_URL }"))
c('XN09e', 'Object.assign(config, { assetPrefix: x })', nc("const config = {}\nObject.assign(config, { assetPrefix: process.env.DOMINIO_A_URL })\nexport default config"))
c('XN09f', "basePath por spread de objeto { ...{ basePath: x } }", nc("const b = { basePath: process.env.X }\nexport default { ...b }"))
c('XN09g', 'controle: assetPrefix condicional de literais (falso positivo?)', nc("export default { assetPrefix: process.env.NODE_ENV === 'production' ? '/cdn' : undefined }"))
c('XN01q', 'config.env por Object.assign', nc("const config = {}\nObject.assign(config, { env: { D: process.env.DOMINIO_A_URL } })\nexport default config"))
c('XN01r', "config['env'] = {...}", nc("const config = {}\nconfig['env'] = { D: process.env.DOMINIO_A_URL }\nexport default config"))
const cli = (f) => analisarSeguranca("'use client'\n" + f, 'x.tsx')
c('XU01', "'use client' process.env['DOMINIO_A_URL'] por indice", cli("export const u = process.env['DOMINIO_A_URL']"))
c('XU02', "'use client' const e = process.env; e.DOMINIO_A_URL", cli("const e = process.env\nexport const u = e.DOMINIO_A_URL"))
c('XU03', "'use client' const { DOMINIO_A_URL } = process.env", cli("const { DOMINIO_A_URL } = process.env\nexport const u = DOMINIO_A_URL"))
// N8: pilha de escopos
c('XR20c', 'constructor(fetch) em classe (JS)', rede("class C { constructor(fetch) { this.f = fetch } }\nexport const g = () => fetch('http://evil')"))
c('XR20d', 'set x(fetch) acessor', rede("class C { set f(fetch) {} }\nexport const g = () => fetch('http://evil')"))
c('XR20e', 'try {} catch (fetch) {} no topo', rede("try { } catch (fetch) { }\nexport const g = () => fetch('http://evil')"))
c('XR20f', 'for (const fetch of []) {} no topo', rede("for (const fetch of []) { }\nexport const g = () => fetch('http://evil')"))
c('XR20g', 'constructor(private WebSocket) e new WebSocket', rede("export class Canal { constructor(private WebSocket: unknown) {} }\nexport const g = () => new WebSocket('ws://evil')"))
c('XR20h', 'constructor(readonly fetch: Fetcher) (injecao TS)', rede("type Fetcher = (u: string) => Promise<unknown>\nexport class Cliente { constructor(readonly fetch: Fetcher) {} }\nexport const g = () => fetch('http://evil')"))
c('XR20i', 'get/set em objeto literal com parametro fetch', rede("const o = { set v(fetch) {} }\nexport const g = () => fetch('http://evil')"))
c('XR20j', 'bloco com const fetch no mesmo nivel do uso (legitimo: sombra real)', rede("export const g = () => { const fetch = (u) => u; return fetch('ok') }"))
c('XR28b', "chave calculada inline 'const'+'ructor' (sem const)", rede("export const x = Object.getPrototypeOf(async function () {})['const' + 'ructor']('return fetch')"))
c('XR28c', 'chave por template com expressao', rede("const a = 'ructor'\nexport const x = Object.getPrototypeOf(async function () {})[`const${a}`]('return fetch')"))
c('XR28d', "chave por array.join", rede("export const x = Object.getPrototypeOf(async function () {})[['const', 'ructor'].join('')]('return fetch')"))
