import { writeFileSync } from 'node:fs'
const EST = 'node --test base/verificacao/saida-de-rede.test.mjs base/verificacao/seguranca-estatica.test.mjs 2>&1'
const E2E = 'task verificar:redis 2>&1'
const s = (id, inv, desc, edicoes, cmd = E2E, env = { CONSTRUIR: '1' }) => ({ id, inv, desc, cmd, env, edicoes })
const Z1 = 'repos/erp-zona-1/', Z2 = 'repos/erp-zona-2/', ZA = 'repos/erp-zona-acesso/'
const PG = Z1 + 'app/zona1/page.tsx'
const ILHA = { arquivo: Z1 + 'app/zona1/BotaoDeAviso.tsx', de: 'export function BotaoDeAviso({ texto }: { texto: string })', para: 'export function BotaoDeAviso({ texto }: { texto: string; extra?: unknown })' }
const BOTAO = '{recursos && <BotaoDeAviso texto={`${recursos.length} recursos visíveis para você`} />}'
const RET = '  return (\n    <>\n      <h1>Painel da zona 1</h1>'
const LR = 'export const listarRecursos = cache(async () =>\n'
const AMB = 'base/scripts/ambiente.mjs'
const REDIS1 = 'export const clienteRedis: ClienteRedisDeLeitura | null = url ? clientePreguicoso(url) : null\n'
const L = [
  // --- catálogo it.4, pego pelo estático (verificar:estatica é subconjunto do verificar:redis)
  s('E10d', 'inv. 2', 'zona1: const envio = { lista: recursos } e extra={envio.lista} (ilha com prop opcional)', [ILHA, { arquivo: PG, de: RET, para: '  const envio = { lista: recursos }\n' + RET }, { arquivo: PG, de: BOTAO, para: '{recursos && <BotaoDeAviso texto="x" extra={envio.lista} />}' }], EST, {}),
  s('E10e', 'inv. 2', 'NOVA (V3 da it.5): extra={envio.resumo} com resumo = recursos (nome fora de CAMPOS_COMPLEXOS)', [ILHA, { arquivo: PG, de: RET, para: '  const envio = { resumo: recursos }\n' + RET }, { arquivo: PG, de: BOTAO, para: '{recursos && <BotaoDeAviso texto="x" extra={envio.resumo} />}' }], EST, {}),
  s('XR20p', 'inv. 4 (N8)', 'zona1 lib/dominio-a.ts: const sombra = (fetch: unknown) => fetch + listarRecursos faz fetch direto para fora', [{ arquivo: Z1 + 'lib/dominio-a.ts', de: LR, para: "const sombra = (fetch: unknown) => fetch\nvoid sombra\n" + LR + "  (await fetch('http://127.0.0.1:4999/xr20p').catch(() => null), 0) ||\n" }], EST, {}),
  s('XR38p', 'inv. 4 (N8)', 'zona2 lib/test/rede.ts (novo) com fetch para fora, importado por lib/pagina.ts', [{ arquivo: Z2 + 'lib/test/rede.ts', novo: true, para: "import 'server-only'\nexport const rede = () => fetch('http://127.0.0.1:4999/xr38').catch(() => null)\n" }, { arquivo: Z2 + 'lib/pagina.ts', de: "import { nucleo } from './nucleo'\n", para: "import { nucleo } from './nucleo'\nimport { rede } from './test/rede'\n" }, { arquivo: Z2 + 'lib/pagina.ts', de: 'const cabecalho = async (nome: string) => (await headers()).get(nome)', para: 'const cabecalho = async (nome: string) => { void rede(); return (await headers()).get(nome) }' }], EST, {}),
  s('XR23p', 'inv. 4 (N8)', "zona-acesso lib/pagina.ts: import Canal from 'next/dist/compiled/ws' e conexao a cada requisicao", [{ arquivo: ZA + 'lib/pagina.ts', de: "import { nucleo } from './nucleo'\n", para: "import { nucleo } from './nucleo'\n// @ts-expect-error sem tipos\nimport Canal from 'next/dist/compiled/ws'\n" }, { arquivo: ZA + 'lib/pagina.ts', de: 'const cabecalho = async (nome: string) => (await headers()).get(nome)', para: "const cabecalho = async (nome: string) => { try { new Canal.WebSocket('ws://127.0.0.1:4999/xr23').on('error', () => {}) } catch {} return (await headers()).get(nome) }" }], EST, {}),
  s('XN01p', 'inv. 11', 'zona2 next.config: config.env = { ZONA2_INTERNO } por atribuicao + process.env.ZONA2_INTERNO na ilha error.tsx', [{ arquivo: Z2 + 'next.config.ts', de: 'export default config', para: "config.env = { ZONA2_INTERNO: process.env.DOMINIO_C_URL ?? 'http://127.0.0.1:4003' }\nexport default config" }, { arquivo: Z2 + 'app/error.tsx', de: '<p>{MENSAGENS.ERRO_INTERNO}</p>', para: '<p>{MENSAGENS.ERRO_INTERNO} {process.env.ZONA2_INTERNO}</p>' }], EST, {}),
  // --- catálogo it.4, pego por teste estático dentro do base.test (sobe a base; build existente basta)
  s('E01b', 'inv. 15', 'zona1 lib/redis.ts: process.env.REDIS_URL // REDIS_URL_ZONA (nome so no comentario)', [{ arquivo: Z1 + 'lib/redis.ts', de: '  const url = process.env.REDIS_URL_ZONA\n', para: '  const url = process.env.REDIS_URL // REDIS_URL_ZONA\n' }], E2E, { CONSTRUIR: '0' }),
  s('E05', 'B3/inv. 10', 'zona1 api/health chama o dominio A e devolve os recursos', [{ arquivo: Z1 + 'app/zona1/api/health/route.ts', de: "export function GET() {\n  return Response.json({ status: 'ok' })\n}", para: "import { listarRecursos } from '@/lib/dominio-a'\nexport async function GET() {\n  return Response.json({ status: 'ok', recursos: await listarRecursos().catch(() => null) })\n}" }], E2E, { CONSTRUIR: '0' }),
  s('P12', 'inv. 5', 'zona1 lib/pagina.ts: hostsPermitidos acrescenta evil.com', [{ arquivo: Z1 + 'lib/pagina.ts', de: "hostsPermitidos: (process.env.SHELL_HOSTS ?? 'localhost:3000').split(','),", para: "hostsPermitidos: [...(process.env.SHELL_HOSTS ?? 'localhost:3000').split(','), 'evil.com']," }], E2E, { CONSTRUIR: '0' }),
  // --- catálogo it.4, comportamento (reconstrói a app mutada)
  s('E01f', 'inv. 15', "zona1 lib/redis.ts: a cada leitura, conexao de passagem com process.env['REDIS_'+'URL'] grava sessao forjada da carla ('s'+'et') e sai com quit", [{ arquivo: Z1 + 'lib/redis.ts', de: '  return { get: async (chave) => (await conectado()).get(chave) }', para: "  return { get: async (chave) => {\n    const w = process.env['REDIS_' + 'URL']\n    if (w) { const c = createClient({ url: w }); c.on('error', () => {}); await c.connect().then((x) => (x as unknown as Record<string, (...a: unknown[]) => Promise<unknown>>)['s' + 'et']!('erp:sessao:HASH_E01F', JSON.stringify({ sub: 'carla', nome: 'Carla', accessToken: 'dev.carla', expiraEm: Date.now() + 86_400_000 }), { EX: 3600 })).then(() => c.quit()).catch(() => {}) }\n    return (await conectado()).get(chave)\n  } }" }], E2E + "; echo '--- prova'; node .agents/auditor_b1_d1_8/anexos/prova-chave.mjs forjada-aud8-e01f 2>&1"),
  s('E01e', 'inv. 15', "zona1 lib/redis.ts: cliente persistente com process.env['REDIS_'+'URL'] (REDIS_URL_ZONA segue no codigo)", [{ arquivo: Z1 + 'lib/redis.ts', de: 'export const clienteRedis: ClienteRedisDeLeitura | null = url ? clientePreguicoso(url) : null', para: "export const clienteRedis: ClienteRedisDeLeitura | null = url ? clientePreguicoso(process.env['REDIS_' + 'URL'] ?? url) : null" }]),
  s('K2a', 'inv. 15', 'zona2 lib/redis.ts: recusa desligada (REDIS_URL sem REDIS_URL_ZONA cai no store em arquivo)', [{ arquivo: Z2 + 'lib/redis.ts', de: "  if (!url && process.env.REDIS_URL) {\n    throw new Error(", para: "  if (false && !url && process.env.REDIS_URL) {\n    throw new Error(" }]),
  s('P16b', 'inv. 6', "zona2 acoes.ts: If-Match fixo '\"3\"'", [{ arquivo: Z2 + 'app/zona2/acoes.ts', de: "ifMatch: `\"${String(form.get('versao') ?? '')}\"`,", para: "ifMatch: '\"3\"'," }]),
  s('P10', 'inv. 8', 'zona1 page: link de Relatorios para todos', [{ arquivo: PG, de: '{relatorios && <p><a href="/zona1/relatorios">Relatórios</a></p>}', para: '{<p><a href="/zona1/relatorios">Relatórios</a></p>}' }]),
  s('P09b', 'inv. 5', 'zona-acesso acoes.ts: nucleo as n e revogacao no 2o argumento do acaoProtegida (avaliado antes), erro engolido', [{ arquivo: ZA + 'app/acesso/acoes.ts', de: "import { nucleo } from '@/lib/nucleo'\n", para: "import { nucleo } from '@/lib/nucleo'\nimport { nucleo as n } from '@/lib/nucleo'\n" }, { arquivo: ZA + 'app/acesso/acoes.ts', de: "  return acaoProtegida(PAPEL, '/acesso', async () => {\n    await nucleo.destino('gestao-acesso').post('/v2/acessos/:id/revogacao',", para: "  return acaoProtegida(PAPEL, (await n.destino('gestao-acesso').post('/v2/acessos/:id/revogacao', { params: { id: texto(f, 'acesso') } }).catch(() => null), '/acesso'), async () => {\n    await nucleo.destino('gestao-acesso').post('/v2/acessos/:id/revogacao'," }]),
  s('P12c', 'inv. 5', 'zona2 lib/pagina.ts: adaptador cabecalho mente origin = shell e sec-fetch-site = same-origin', [{ arquivo: Z2 + 'lib/pagina.ts', de: 'const cabecalho = async (nome: string) => (await headers()).get(nome)', para: "const cabecalho = async (nome: string) => nome === 'origin' ? 'http://localhost:3000' : nome === 'sec-fetch-site' ? 'same-origin' : (await headers()).get(nome)" }]),
  s('SEM1', 'inv. 6', 'stub dados/semente/dominio-c.json: t-1 de volta a versao 1', [{ arquivo: 'repos/erp-dominio-stub/dados/semente/dominio-c.json', de: '"concluida": false, "versao": 3 }', para: '"concluida": false, "versao": 1 }' }]),
  // --- K3/K4: produto que passou pelo estático (efeito no alvo 4999)
  s('XR20q', 'inv. 4 (N8)', 'NOVA: zona1 lib/dominio-a.ts: classe com constructor(fetch) (injecao de dependencia) + listarRecursos faz fetch direto para fora', [{ arquivo: Z1 + 'lib/dominio-a.ts', de: LR, para: "export class Transporte { enviar: (u: string) => Promise<unknown>; constructor(fetch: (u: string) => Promise<unknown>) { this.enviar = fetch } }\n" + LR + "  (await fetch('http://127.0.0.1:4999/xr20q').catch(() => null), 0) ||\n" }]),
  // --- K3/K4: ambiente
  s('AMB1', 'inv. 15', 'NOVA: iniciar ignora envProc (revert do K4-3)', [{ arquivo: AMB, de: '{ cwd, env: envProc, stdio:', para: '{ cwd, env, stdio:' }], E2E, { CONSTRUIR: '0' }),
  s('AMB2', 'inv. 15', 'NOVA: envDaApp nao apaga REDIS_URL', [{ arquivo: AMB, de: '    delete envZona.REDIS_URL\n', para: '' }], E2E, { CONSTRUIR: '0' }),
  s('AMB3', 'inv. 15', 'NOVA: envDoDominio mantem REDIS_URL_ZONA', [{ arquivo: AMB, de: '  delete envDoDominio.REDIS_URL_ZONA\n', para: '' }], E2E, { CONSTRUIR: '0' }),
  s('AMB4', 'inv. 15', 'NOVA: subirDominio (dominio que volta no meio da verificacao) sobe com env inteiro', [{ arquivo: AMB, de: "dominios.set(nome, iniciar('node', ['src/servidor.mjs', nome], join(RAIZ, 'erp-dominio-stub'), envDoDominio))\n    await esperar(`http://127.0.0.1:${PORTA[nome]}/`)", para: "dominios.set(nome, iniciar('node', ['src/servidor.mjs', nome], join(RAIZ, 'erp-dominio-stub'), env))\n    await esperar(`http://127.0.0.1:${PORTA[nome]}/`)" }], E2E, { CONSTRUIR: '0' }),
  s('AMB5', 'inv. 15', 'NOVA: subirApp (zona que volta no meio da verificacao) sobe com env inteiro', [{ arquivo: AMB, de: "apps.set(dir, iniciar('pnpm', ['start'], join(RAIZ, dir), envDaApp(dir)))\n    const { porta, saude }", para: "apps.set(dir, iniciar('pnpm', ['start'], join(RAIZ, dir), env))\n    const { porta, saude }" }], E2E, { CONSTRUIR: '0' }),
  s('AMB6', 'inv. 15', 'NOVA: registrar (pnpm registrar da zona) roda com env inteiro (REDIS_URL)', [{ arquivo: AMB, de: "execFileSync('pnpm', ['registrar'], { cwd: join(RAIZ, dir), env: envDaApp(dir),", para: "execFileSync('pnpm', ['registrar'], { cwd: join(RAIZ, dir), env," }], E2E, { CONSTRUIR: '0' }),
  s('TF1', 'inv. 15', 'NOVA: Taskfile verificar:redis com REDIS_URL sem senha (revert do K4-4)', [{ arquivo: 'Taskfile.yml', de: 'REDIS_URL: redis://default:dev-shell-escrita@127.0.0.1:6379', para: 'REDIS_URL: redis://127.0.0.1:6379' }], E2E, { CONSTRUIR: '0' }),
]
writeFileSync(new URL('./C.json', import.meta.url), JSON.stringify(L, null, 1).replace('HASH_E01F', require_hash()))
function require_hash() { return 'ff9dc6dde67e568c927bac5a172a7e10e77b774648d98c094483a275d4f5b1b4' }
